### ISSUE TITLE
[Bug] TFE Provider v0.26.0 does not default hostname

### ISSUE THREAD

**Issue by straubt1** [hashicorp/terraform-provider-tfe#356] opened 2021-09-03 15:22 UTC
#### Terraform Cloud/Enterprise version

Terraform Cloud

#### Terraform version

```plaintext
Terraform v1.0.5
```

#### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    tfe = {
      version = "= 0.26.0"
    }
  }
}

resource "tfe_workspace" "test" {
  organization = "terraform-tom"
  name         = "test1"
}
```

#### Debug Output

```plaintext
╷
│ Error: Invalid provider configuration
│ 
│ Provider "registry.terraform.io/hashicorp/tfe" requires explicit configuration. Add a provider block to the root module and configure the provider's required
│ arguments as described in the provider documentation.
│ 
╵
╷
│ Error: Error retrieving provider meta values from provider request
│ 
│   with provider["registry.terraform.io/hashicorp/tfe"],
│   on <empty> line 0:
│   (source code not available)
│ 
│ Error retrieving provider meta values from provider request the hostname and token must be present.
```

#### Expected Behavior

TFE_TOKEN is set as an env variable, but TFE_HOSTNAME is not (it should default to TFC, app.terraform.io).

`terraform plan` should execute without error.

#### Actual Behavior

Error with provider version 0.26.0, but works as expected with 0.25.3
It appears the provider is not defaulting TFE_HOSTNAME anymore.

**Comment by chrisarcand** [comment] 2021-09-03 15:36
Dupe of #353

**Closed** 2021-09-03 15:41 UTC
Labels: bug
