### ISSUE TITLE
Plugin crashed when re-applying unchanged tfe_registry_module config with tests_enabled undefined

### ISSUE THREAD

**Issue by richard-russell** [hashicorp/terraform-provider-tfe#1201] opened 2024-01-03 18:18 UTC
#### Terraform Cloud/Enterprise version

Terraform Cloud

#### Terraform version

```plaintext
1.6.3
```

#### Provider version
```plaintext
0.51.1
```

#### Terraform Configuration Files

```terraform
resource "tfe_registry_module" "awslz" {
  organization = var.tfc_organization
  vcs_repo {
    display_identifier = "${var.github_owner}/terraform-tfe-nocode-lz"
    identifier         = "${var.github_owner}/terraform-tfe-nocode-lz"
    oauth_token_id     = var.oauth_token_id
    branch             = "main"
  }
}
```

#### Debug Output

```plaintext
Stack trace from the terraform-provider-tfe_v0.51.1_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc8 pc=0xc9758c]

goroutine 12 [running]:
github.com/hashicorp/terraform-provider-tfe/internal/provider.resourceTFERegistryModuleUpdate(0x0?, {0xe46a00?, 0xc000414e88?})
	github.com/hashicorp/terraform-provider-tfe/internal/provider/resource_tfe_registry_module.go:339 +0x8ec
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x1066508?, {0x1066508?, 0xc00057e360?}, 0xd?, {0xe46a00?, 0xc000414e88?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/resource.go:800 +0x163
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003035e0, {0x1066508, 0xc00057e360}, 0xc0003c5380, 0xc00004d280, {0xe46a00, 0xc000414e88})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/resource.go:919 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000011188, {0x1066508?, 0xc00057e270?}, 0xc000432f50)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/grpc_provider.go:1072 +0xdbc
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0x1066540?, {0x1066508?, 0xc000445f50?}, 0xc000432f50)
	github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000222e60, {0x1066508?, 0xc000445560?}, 0xc0000ee700)
	github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov5/tf5server/server.go:859 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xebacc0?, 0xc000222e60}, {0x1066508, 0xc000445560}, 0xc00004c980, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:503 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00027c1e0, {0x1066508, 0xc0004454d0}, {0x106c3b8, 0xc0004069c0}, 0xc00056c5a0, 0xc000321ec0, 0x1686b58, 0x0)
	google.golang.org/grpc@v1.60.0/server.go:1372 +0xe03
google.golang.org/grpc.(*Server).handleStream(0xc00027c1e0, {0x106c3b8, 0xc0004069c0}, 0xc00056c5a0)
	google.golang.org/grpc@v1.60.0/server.go:1783 +0xfec
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.60.0/server.go:1016 +0x59
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 23
	google.golang.org/grpc@v1.60.0/server.go:1027 +0x115

Error: The terraform-provider-tfe_v0.51.1_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Operation failed: failed running terraform apply (exit 1)
```

#### Expected Behavior

On first apply Terraform should create the registry module with `branch` defined in the VCS block, and with no `test_config` block. Subsequent applies with unchanged config should be no-op.

#### Actual Behavior

On first apply Terraform creates the registry module correctly. On second apply the TFE provider plugin crashes trying to execute this plan:
```
  # tfe_registry_module.awslz will be updated in-place
  ~ resource "tfe_registry_module" "awslz" {
        id                   = "mod-XgGwPzjSUCVoXFWa"
        name                 = "nocode-lz"
        # (6 unchanged attributes hidden)

      - test_config {
          - tests_enabled = false -> null
        }

        # (1 unchanged block hidden)
    }
```
#### Additional Context

The problem does not happen when `tests_enabled` is explicitly set to `false`.
```terraform
resource "tfe_registry_module" "awslz" {
  organization = var.tfc_organization
  vcs_repo {
    display_identifier = "${var.github_owner}/terraform-tfe-nocode-lz"
    identifier         = "${var.github_owner}/terraform-tfe-nocode-lz"
    oauth_token_id     = var.oauth_token_id
    branch             = "main"
  }
  test_config {
    tests_enabled = false
  }
}
```

**Comment by aaabdelgany** [comment] 2024-04-08 17:41
Hello @richard-russell, I took a look at this and was unable to reproduce it. Do you mind confirming if you're still seeing the issue?

**Comment by aaabdelgany** [comment] 2024-04-23 20:54
Closing for now since I'm unable to repro this. Please feel free to reopen it or open a new issue if you come across it again.

**Closed by aaabdelgany** 2024-04-23 20:54 UTC
Labels: bug
