### ISSUE TITLE
[Feature Request] tfe_oauth_client: import resource and data source

### ISSUE THREAD

**Issue by kuroseets** [hashicorp/terraform-provider-tfe#203] opened 2020-08-13 11:08 UTC
I think that we use tfe_oauth_client.id often. but we cannot get already exist tfe_oauth_client object.
It is inconvenience because VSC Settings are often set using the GUI.

**Comment by bendrucker** [comment] 2020-08-13 16:19
Keep in mind that you'd need to pass the OAuth secret (`oauth_token`) separately, since the API does not return it. The typical pattern for this is to use an environment variable, e.g.:

```sh
TFE_OAUTH_TOKEN=$TOKEN terraform import tfe_oauth_client.foo oc-XKFwG6ggfA9n7t1K
```

This should be an easy-ish PR if you're so inclined! 🙂

**Comment by A30004028** [comment] 2020-08-14 01:27
Check out the data source created by HappyPathway for getting it from the API, youshould be able to use it as a basis for what you need to get at. Then publish it as a module

https://github.com/HappyPathway/terraform-tfe-oauth-token

**Comment by kuroseets** [comment] 2020-08-14 10:27
>bendruckr
Thank you, I try it.

>A30004098
Thank you.
I know we can get oauth id at API, I use now. But it is not I want.
I want to get on terraform code and to administrate its object.

**Comment by FlorentATo** [comment] 2022-10-04 22:56
Gentle bump, our Terraform Cloud configuration isn't complete without this resource. Thank you :)

**Comment by annawinkler** [comment] 2022-10-05 23:35
👋 Hi! Thank you for the bump on this issue. You know, I noticed that we added the [resource](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/oauth_client)
and the [data source](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/data-sources/oauth_client) 

From what I understand of this request, I think that the issue is resolved. Is there anything missing? @FlorentATo @kuroseets

**Comment by annawinkler** [comment] 2022-12-21 01:04
👋 Hi @FlorentATo and @kuroseets - checking in again about this request. I think we've addressed the request. I'll go ahead and close this issue. Please feel free to reopen if something is missing.

**Closed by annawinkler** 2022-12-21 01:04 UTC
Labels: feature-request
