### ISSUE TITLE
Changes in workspaces data source collection causes inconsistent plan during variable_set workspace attachment

### ISSUE THREAD

**Issue by cforain** [hashicorp/terraform-provider-tfe#496] opened 2022-05-11 00:49 UTC
#### Terraform Cloud/Enterprise version
We are using Terraform Cloud

#### Terraform version
```plaintext
terraform -v
Terraform v1.1.9
on darwin_amd64
+ provider registry.terraform.io/hashicorp/tfe v0.31.0
```
We are running this through a CLI-driven TFC workspace. This is our workspace backend configuration:

```tf
terraform {
  required_version = "~> 1.1.9"

  required_providers {
    tfe = {
      version   = "~> 0.31.0"
    }
  }

  cloud {
    organization = "my-org"
    workspaces {
      name = "claudio-cli"
    }
  }
}
``` 

#### Terraform Configuration Files
What we are trying to achieve is really straightforward, directly from your documentation [here](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/workspace), which is to filter some `workspaces` by name/tag and attach them to a newly created `variable set`

So after running  `terraform apply` on the following configuration, 2 workspaces will be created as expected and output their IDs:

```tf
locals {
  workspace_names = ["claudio-cli-ws1","claudio-cli-ws2"]
}

resource "tfe_workspace" "claudio-cli-ws" {
  for_each = toset(local.workspace_names)
  name         = each.key
  organization = "my-org"
  tag_names    = ["team:claudio-cli"]
}


data "tfe_workspace_ids" "claudio-cli-ws-ids" {
  names = []
  tag_names = ["team:claudio-cli"]
  organization = "my-org"
}

output "out" {
  value = data.tfe_workspace_ids.claudio-cli-ws-ids.ids
}
```

Output:
````
Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

Outputs:

out = tomap({
  "claudio-cli-ws1" = "ws-NZSgT1A6R1CebArW"
  "claudio-cli-ws2" = "ws-H5mGYmFf6XhbqwXW"
})
````

Afterwards, if I add the following `tfe_variable_set` resource block and use the `tfe_workspace_ids` data source filtered by `team:claudio-cli` tag and attach them to a newly created `tfe_variable_set` block, like this:

```tf
resource "tfe_variable_set" "test-varset" {
  name          = "cli test Varset"
  description   = "${join(",", (keys(data.tfe_workspace_ids.claudio-cli-ws-ids.ids)))}"
  organization  = "my-org"
  workspace_ids = values(data.tfe_workspace_ids.claudio-cli-ws-ids.ids)
}

```

And run `terraform apply` again, will create the `variable set` and attach it to the workspaces, as expected. Output:

```
Terraform will perform the following actions:

  # tfe_variable_set.test-varset will be created
  + resource "tfe_variable_set" "test-varset" {
      + description   = "claudio-cli-ws1,claudio-cli-ws2"
      + global        = false
      + id            = (known after apply)
      + name          = "cli test Varset"
      + organization  = "my-org"
      + workspace_ids = [
          + "ws-H5mGYmFf6XhbqwXW",
          + "ws-NZSgT1A6R1CebArW",
        ]
    }

...

tfe_variable_set.test-varset: Creating...
tfe_variable_set.test-varset: Creation complete after 2s [id=varset-JR6KG6sKPetg4jKQ]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

out = tomap({
  "claudio-cli-ws1" = "ws-NZSgT1A6R1CebArW"
  "claudio-cli-ws2" = "ws-H5mGYmFf6XhbqwXW"
})
```

So far so good, but now things get more interesting. If I make any change on the code that might change the collection returned by the `tfe_workspace_ids` data source (for instance, adding or removing a workspace), the data source isn't refreshed during the run, and any change gets ignored, so terraform uses the values from the beginning of the run (`plan` phase). 

So, for instance if I know change this block from this:
```tf
locals {
  workspace_names = ["claudio-cli-ws1","claudio-cli-ws2"]
}
```
To this:

```tf
locals {
  workspace_names = ["claudio-cli-ws1","claudio-cli-ws2", "claudio-cli-ws3"]
}
```
And run `terraform apply` again, what happens is that the newly created workspace **DOES NOT** get attached to the `variable set` on the run:

```
Terraform will perform the following actions:

  # tfe_workspace.claudio-cli-ws["claudio-cli-ws3"] will be created
  + resource "tfe_workspace" "claudio-cli-ws" {
     .
     .
     .
    }

Plan: 1 to add, 0 to change, 0 to destroy.

...

out = tomap({
  "claudio-cli-ws1" = "ws-NZSgT1A6R1CebArW"
  "claudio-cli-ws2" = "ws-H5mGYmFf6XhbqwXW"
})
```

However, interestingly enough, if I immediately run `terraform apply` again, with no changes to code nor environment whatsoever, it **DOES** get attached:
```
Terraform will perform the following actions:

  # tfe_variable_set.test-varset will be updated in-place
  ~ resource "tfe_variable_set" "test-varset" {
      ~ description   = "claudio-cli-ws1,claudio-cli-ws2" -> "claudio-cli-ws1,claudio-cli-ws2,claudio-cli-ws3"
        id            = "varset-JR6KG6sKPetg4jKQ"
        name          = "cli test Varset"
      ~ workspace_ids = [
          + "ws-RXPMeDymCdst9JwA",
            # (2 unchanged elements hidden)
        ]
        # (2 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

...

out = tomap({
  "claudio-cli-ws1" = "ws-NZSgT1A6R1CebArW"
  "claudio-cli-ws2" = "ws-H5mGYmFf6XhbqwXW"
  "claudio-cli-ws3" = "ws-RXPMeDymCdst9JwA"
})
```
This behavior seems to have been corrected on `v0.12` according to [this issue](https://github.com/hashicorp/terraform/issues/21176), but somehow still happens for this provider on `1.1.9`.

So, as a workaround, I thought that maybe adding an explicit dependency to the `tfe_workspace_ids` data source might solve the issue, so I added the `depends_on` block to the data source, like this:

```tf
data "tfe_workspace_ids" "claudio-cli-ws-ids" {
  depends_on = [tfe_workspace.claudio-cli-ws] //added this
  names = []
  tag_names = ["team:claudio-cli"]
  organization = "my-org"
}
```
 and repeated the experiment. What happens is that it seems the data source gets the correct updated collection and tries to attach it on the same run  during `terraform plan` as expected : 

```
Terraform will perform the following actions:

  # data.tfe_workspace_ids.claudio-cli-ws-ids will be read during apply
  # (config refers to values not yet known)
 <= data "tfe_workspace_ids" "claudio-cli-ws-ids"  {
      ~ full_names   = {
          - "claudio-cli-ws1" = "my-org/claudio-cli-ws1"
          - "claudio-cli-ws2" = "my-org/claudio-cli-ws2"
        } -> (known after apply)
      ~ id           = "my-org/864842328" -> (known after apply)
      ~ ids          = {
          - "claudio-cli-ws1" = "ws-NZSgT1A6R1CebArW"
          - "claudio-cli-ws2" = "ws-H5mGYmFf6XhbqwXW"
        } -> (known after apply)
      + names        = []
        # (2 unchanged attributes hidden)
    }

  # tfe_variable_set.test-varset will be updated in-place
  ~ resource "tfe_variable_set" "test-varset" {
      ~ description   = "claudio-cli-ws1,claudio-cli-ws2" -> (known after apply)
        id            = "varset-JR6KG6sKPetg4jKQ"
        name          = "cli test Varset"
        # (3 unchanged attributes hidden)
    }

  # tfe_workspace.claudio-cli-ws["claudio-cli-ws3"] will be created
  + resource "tfe_workspace" "claudio-cli-ws" {
      + allow_destroy_plan            = true
      + auto_apply                    = false
      + execution_mode                = (known after apply)
      + file_triggers_enabled         = true
      + global_remote_state           = (known after apply)
      + id                            = (known after apply)
      + name                          = "claudio-cli-ws3"
      + operations                    = (known after apply)
      + organization                  = "my-org"
      + queue_all_runs                = true
      + remote_state_consumer_ids     = (known after apply)
      + speculative_enabled           = true
      + structured_run_output_enabled = true
      + tag_names                     = [
          + "team:claudio-cli",
        ]
      + terraform_version             = (known after apply)
      + trigger_prefixes              = (known after apply)
    }

Plan: 1 to add, 1 to change, 0 to destroy.

Changes to Outputs:
  ~ out = {
      - "claudio-cli-ws1" = "ws-NZSgT1A6R1CebArW"
      - "claudio-cli-ws2" = "ws-H5mGYmFf6XhbqwXW"
    } -> (known after apply)
```

However, fails horribly during `terraform apply`:

```
 Error: Provider produced inconsistent final plan
 
 When expanding the plan for tfe_variable_set.test-varset to include new
 values learned so far during apply, provider
 "registry.terraform.io/hashicorp/tfe" produced an invalid new value for
 .workspace_ids: actual set element cty.StringVal("ws-wsViYS7YAXWceWHq")
 does not correlate with any element in plan.

  ... 

 When expanding the plan for tfe_variable_set.test-varset to include new
 values learned so far during apply, provider
 "registry.terraform.io/hashicorp/tfe" produced an invalid new value for
 .workspace_ids: length changed from 2 to 3.
 
 This is a bug in the provider, which should be reported in the provider's
 own issue tracker.
```

It is worth noting that the id `ws-wsViYS7YAXWceWHq` mentioned on the error, does exist, as the `apply` indeed created the new workspace. So if, once again with no changes whatsoever, I run `terraform apply` again, it works as expected, as the data source doesn't change during the run:

```
Terraform will perform the following actions:

  # tfe_variable_set.test-varset will be updated in-place
  ~ resource "tfe_variable_set" "test-varset" {
      ~ description   = "claudio-cli-ws1,claudio-cli-ws2" -> "claudio-cli-ws1,claudio-cli-ws2,claudio-cli-ws3"
        id            = "varset-JR6KG6sKPetg4jKQ"
        name          = "cli test Varset"
      ~ workspace_ids = [
          + "ws-wsViYS7YAXWceWHq",
            # (2 unchanged elements hidden)
        ]
        # (2 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

...

tfe_variable_set.test-varset: Modifying... [id=varset-JR6KG6sKPetg4jKQ]
tfe_variable_set.test-varset: Modifications complete after 0s [id=varset-JR6KG6sKPetg4jKQ]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

Outputs:

out = tomap({
  "claudio-cli-ws1" = "ws-NZSgT1A6R1CebArW"
  "claudio-cli-ws2" = "ws-H5mGYmFf6XhbqwXW"
  "claudio-cli-ws3" = "ws-wsViYS7YAXWceWHq"
})
```

As this really looks like some kind of racing condition, I tried to add a delay between the data source fetch and the `variable set` creation by adding a 10 second delay, to no avail:

```tf
locals {
  varset_delay = "10s"
  ws_ids_list = join(",", sort(values(data.tfe_workspace_ids.ws_ids.ids)))
  ws_names_list = join(", ", keys(data.tfe_workspace_ids.ws_ids.ids))
}
resource "time_sleep" "delay_varset" {
  depends_on = [data.tfe_workspace_ids.ws_ids]
  create_duration = local.varset_delay
  destroy_duration = local.varset_delay

  # this tells to trigger a resource change anytime the collection of workspace ids change
  triggers = {
    workspace_ids = local.ws_ids_list
  }
}

resource "tfe_variable_set" "varset" {
  depends_on = [time_sleep.delay_varset]
  name          = var.variable_set.name
  description   = "Variable Set applied to: ${local.ws_names_list}"
  organization  = "my-org"
  workspace_ids = split(",", time_sleep.delay_varset.triggers["workspace_ids"]) #values(data.tfe_workspace_ids.ws_ids.ids)
}
```
It is worth mentioning that there was a [similar reported issue](https://github.com/hashicorp/terraform-provider-aws/issues/10297) on the `aws` provider, besides the aforementioned [core one](https://github.com/hashicorp/terraform/issues/21176).

#### Expected Behavior
Variables sets should attach to workspaces in one run, regardless of how many workspaces might have been created/deleted.

#### Actual Behavior
Whenever there is change on the `tfe_workspace_ids` returned workspaces collection, it gets ignored if implicit dependencies change during `apply`, and crash if dependencies are explicitly declared.

#### Additional Context
This happens regardless the workspaces is VCS or CLI driven.
Similar past issues:
https://github.com/hashicorp/terraform-provider-aws/issues/10297
https://github.com/hashicorp/terraform/issues/21176

Complete code:

```tf


locals {
  workspace_names = ["claudio-cli-ws1","claudio-cli-ws2", "claudio-cli-ws3"]
}

resource "tfe_workspace" "claudio-cli-ws" {
  for_each = toset(local.workspace_names)
  name         = each.key
  organization = "my-org"
  tag_names    = ["team:claudio-cli"]
}


data "tfe_workspace_ids" "claudio-cli-ws-ids" {
  depends_on = [tfe_workspace.claudio-cli-ws]
  names = []
  tag_names = ["team:claudio-cli"]
  organization = "my-org"
}

resource "tfe_variable_set" "test-varset" {
  name          = "cli test Varset"
  description   = "${join(",", (keys(data.tfe_workspace_ids.claudio-cli-ws-ids.ids)))}"
  organization  = "my-org"
  workspace_ids = values(data.tfe_workspace_ids.claudio-cli-ws-ids.ids)
}

output "out" {
  value = data.tfe_workspace_ids.claudio-cli-ws-ids.ids
}
```

**Comment by andrewmaledy** [comment] 2022-06-10 20:24
Hi @teamterraform, we were wondering if the team would be able to take a look at this issue since our enterprise team is relying on this feature to complete our implementation of Terraform Cloud. I am sure the team is busy and that you've got a wide variety of other priorities so any help or workaround you can provide would be really appreciated.

Thank you so much!

Andrew

**Comment by sebasslash** [comment] 2022-06-13 19:49
Hi Claudio! Thank you for reporting this issue. I can confirm I have been able to reproduce this on my end, but fail to see the issue that could be causing this. I will investigate further 👍

**Comment by apparentlymart** [comment] 2022-06-13 22:58
Hi @cforain,

Having one part of a configuration read something that is managed by another part of the configuration can sometimes get into this sort of "one step behind" situations, it does seem to me that what you tried here should have worked in principle. It's weird that the plan just before the error about the inconsistent final plan didn't include a change to the workspace IDs associated with the variable sets, like this:

```
  # tfe_variable_set.test-varset will be updated in-place
  ~ resource "tfe_variable_set" "test-varset" {
      ~ description   = "claudio-cli-ws1,claudio-cli-ws2" -> (known after apply)
        id            = "varset-JR6KG6sKPetg4jKQ"
        name          = "cli test Varset"
      ~ workspace_ids = [
          - "ws-NZSgT1A6R1CebArW"
          - "ws-H5mGYmFf6XhbqwXW"          
        ] -> (known after apply)
        # (3 unchanged attributes hidden)
    }
```

I think there is something more to understand here, which we can investigate, but in the meantime I think you could address this by dropping the intermediate `data` block and deriving the same information directly from `tfe_workspace.claudio-cli-ws` instead:

```hcl
locals {
  workspace_ids = {
    for ws in fe_workspace.claudio-cli-ws : ws.name => ws.id
  }
}

resource "tfe_variable_set" "test-varset" {
  name          = "cli test Varset"
  description   = join(",", keys(local.workspace_ids))
  organization  = "my-org"
  workspace_ids = values(local.workspace_ids)
}
```

This approach avoids trying to read back the same objects that Terraform might be changing in the same run, and instead takes the results directly from the resource that's managing the objects, avoiding that extra request entirely.

I would like to make what you tried work because it does look like there's a bug somewhere, but if this simpler version works then I'd suggest using it even once the bug is fixed, because wiring resources together directly is typically easier to follow and more reliable than asking Terraform to read from the remote system data it already has in its in-memory state anyway.

**Comment by nfagerlund** [comment] 2022-06-14 23:11
I agree with @apparentlymart's analysis!

- The "one step behind" problems were to be expected, and should be resolved by adding that `depends_on` argument (or alternately, a reference to an attribute on the resource). (That PR that fixed the data resource lag in 0.12 relies on dependency information to perform those late fetches, so there needs to be _something_ in the config to indicate that the data source and the resource are related.) 
- That plan _definitely_ should have included a change to `workspace_ids` on that varset resource, and the fact that it didn't is highly sus! 

The one thing I'm noticing is that the `workspace_ids` argument is set to both Optional and Computed: 

```go
			"workspace_ids": {
				Type:     schema.TypeSet,
				Optional: true,
				Computed: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
			},
```

I wonder if that has anything to do with it?

**Comment by nfagerlund** [comment] 2022-06-14 23:46
Hmmmmmmm. 

https://github.com/hashicorp/terraform-plugin-sdk/blob/f0699c2f1489575e3bdb51914d866afa5e936207/helper/schema/schema.go#L533-L547

I found output from this in the TF_LOG=trace output, and it smells potentially relevant. Continuing to dig.

**Comment by cforain** [comment] 2022-06-14 23:54
@apparentlymart thanks for looking into it. The approach you suggested isn't viable for us, because not necessarily the workspaces are being created one-shot, in the same run (nor on the same file, not even maybe by the same team), like it is on this reduced debug code. Other teams/individuals might be creating/destroying workspaces and/or changing tags during the run. The data source is supposedly the way to ensure the run has the latest state from TFC, which should be our ultimate source of truth rather than just our current run. 

The use-case we are trying to tackle is to attach **EXISTING** variable sets to **EXISTING** workspaces, and our solution was to create a module to create variable sets, specifically, and the module accepts a list of names and/or tags to select which workspaces will have the variable set attached to them, hence the data source. This module might or might **NOT** be called on the same run as the workspace module.


The reason for this is that when you guys released the `variable_set` resource, we were caught by surprise that it seems there is no obvious way to simply attach **EXISTING** variable sets to **EXISTING** workspaces (as per [this discussion](https://githublab.com/repository/issues/hashicorp/terraform-provider-tfe/467) ), much like you can attach **EXISTING** teams to **EXISTING** users, through the [tfe_team_access](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/team_access) resource.

On our case, a team might create workspaces, and another team (it might or might not be on the same tf file/run) want arbitrary variable sets attached to these workspaces. Just to be clear, probably most of our problems would be solved if there was a way to arbitrarily attach workspaces and variable sets that way, and not only during variable set creation; because then we could do the opposite: pass existing variable set names to our workspace module, and then attach it once the workspace is created.

Also, @nfagerlund , not sure what it means to have `something` on the config, since we tried explicit dependencies too, which brings up the error rather than TF ignoring the change altogether. I just recently tried declaring chained explicit dependencies on the variable set too: `workspaces -> data ws_ids source -> variable set` , much to the same results. Full code below:

```tf
locals {
  workspace_names = ["claudio-cli-ws1","claudio-cli-ws2", "claudio-cli-ws3"]
}

resource "tfe_workspace" "claudio-cli-ws" {
  for_each = toset(local.workspace_names)
  name         = each.key
  organization = "my-org"
  tag_names    = ["team:claudio-cli"]
}


data "tfe_workspace_ids" "claudio-cli-ws-ids" {
  depends_on = [tfe_workspace.claudio-cli-ws]
  names = []
  tag_names = ["team:claudio-cli"]
  organization = "my-org"
}

resource "tfe_variable_set" "test-varset" {
  depends_on = [data.tfe_workspace_ids.claudio-cli-ws-ids]
  name          = "cli test Varset"
  description   = "${join(",", (keys(data.tfe_workspace_ids.claudio-cli-ws-ids.ids)))}"
  organization  = "procore"
  workspace_ids = values(data.tfe_workspace_ids.claudio-cli-ws-ids.ids)
}

output "out" {
  value = data.tfe_workspace_ids.claudio-cli-ws-ids.ids
}
```

I guess I could @apparentlymart suggestion work, if I pass the output of the workspace module (the ids in that case) as input parameters directly on our variable set module. However, we are trying to avoid that, for a bunch of reasons (our patterns and usability, as we are using yaml files to wrap these), and honestly, as you guys pointed out yourselves, this should work, right? We can do this workaround, but ideally, it would be way better if this worked as intended/documented. Looking forward for the fix, thanks in advance. Cheers.

**Comment by sebasslash** [comment] 2022-07-05 19:36
So new update: with the introduction of #537 `r/tfe_workspace_variable_set`, we now have a simpler way to manage variable set assignments. This resource models a one-to-one relationship and can make use of the additive/subtractive endpoints instead of overwriting all variable set assignments to a workspace. Therefore `workspace_ids` will soon be deprecated as an argument and will remain solely as a computed attribute. This new resource has not been released yet, but will be available in `v0.33.0`.

I'm going to go ahead and close this issue upon release. If you find that `r/tfe_workspace_variable_set` does not fix your issue feel free to go ahead and reopen. Hope this helps!

**Closed** 2022-07-12 23:09 UTC
Labels: bug, confirmed

**Comment by cforain** [comment] 2022-07-14 21:57
Thanks for the the input. The data source usage here is just a reduced code from our current use case, where we would fetch data sources by tag on different runs and/or pieces of code, which is why using the resources output (ids in that case) directly wouldn't be specially useful for us.

That being said, I think we can work with just not creating workspaces at the same time we apply the variable set. I will open a thread on the forum if I bump into other blockers. Cheers.

**Comment by krogon** [comment] 2022-10-20 09:45
Error from last codebase: `The "for_each" value depends on resource attributes that cannot be determined until apply`

Change
```
resource tfe_workspace_variable_set "test" {
  depends_on = [data.tfe_workspace_ids.claudio-cli-ws-ids, tfe_variable_set.test-varset]

  for_each = tfe_workspace.claudio-cli-ws
  workspace_id = each.value.id
  variable_set_id = tfe_variable_set.test-varset.id
}
```

into
```
resource tfe_workspace_variable_set "test" {
  depends_on = [data.tfe_workspace_ids.claudio-cli-ws-ids, tfe_variable_set.test-varset]

  for_each = toset(local.workspace_names)
  workspace_id = tfe_workspace.claudio-cli-ws[each.key].id
  variable_set_id = tfe_variable_set.test-varset.id
}
```
