### ISSUE TITLE
Error: wait: remote command exited without exit status or exit signal

### ISSUE THREAD

**Issue by dkirrane** [hashicorp/terraform-provider-tfe#424] opened 2022-01-28 16:09 UTC
#### Terraform Cloud/Enterprise version

Terraform Cloud 

#### Terraform version

0.15.0

#### Debug Output

```plaintext
module.workspaces["dev-14"].tfe_variable.vars["subscription"]: Creation complete after 3s [id=var-eABSrjPLfhMQVakQ]

Error: wait: remote command exited without exit status or exit signal
```

The tfe apply fails with above error. I can see the workspaces get created in Terraform Cloud but are not in Terraform state. 
So on re-run we hit 
```
Error: Error creating workspace dev-14 for organization XYZ: invalid attribute
│ 
│ Name has already been taken
```

#### Additional Context
Our Terraform tfe config is managed by a single Terrafrom Cloud workspace. It creates all other workspaces for development, performance, test and production.
It looks like it is tethering on the edge of max that can be managed by a single tfe plan.
We now hit `Error: wait: remote command exited without exit status or exit signal`

Maybe we should have split tfe config up into different workspaces? I'm not sure if there is a recommendation here?

**Comment by sebasslash** [comment] 2022-07-14 21:44
Hello! Thanks for reporting the issue. 

Unfortunately, without more information about your configuration there's little guidance to offer here. If I had to guess there's some underlying issue with the script your using with Terraform's remote provisioner (`remote-exec`). In v0.15, there were cases of provider error messages leaking without Terraform being able to properly annotate which resource they originated from. Again these are shots in the dark. 

Your best bet, if you haven't done so already, would be to upgrade your Terraform version to v1.2 so Terraform can properly annotate the error message and help you find the root cause. In order to upgrade your TFC workspace's Terraform version, you'll want to use [Empty Apply Runs](https://www.terraform.io/cloud-docs/run/modes-and-options#allow-empty-apply). 

I'm going to go ahead and close the issue since this is out of scope for the TFE provider.  Apologies!

**Closed by sebasslash** 2022-07-14 21:44 UTC
Labels: bug
