### ISSUE TITLE
Decouple State remote_state_consumer_ids from the workspace object

### ISSUE THREAD

**Issue by rorychatterton** [hashicorp/terraform-provider-tfe#355] opened 2021-09-03 03:20 UTC
Today the [remote_state_consumer_ids](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/workspace#remote_state_consumer_ids) attribute is owned by the workspace resource.

It would be beneficial if this relationship was manageable as a separate object, similar to how we do this with run_triggers today.

#### Use-cases
We have use cases where a workspace provisions another workspace, and then immediately needs access to the upstream workspace's outputs. In essence:

`Workspace A -----Provisions-----> Workspace B`
`Workspace B -----Consumes-----> Workspace A's Outputs`

It is not currently possible for Workspace A to both provision the second workspace, and provide it access to its state, using raw terraform.

#### Attempted Solutions
N/A

#### Proposal
A resource object to create relationships between workspaces for state
```
resource "tfe_workspace_remote_state_consumer_ids" {
  workspace_id  = tfe_workspace.test-workspace.id
  consumer_id = tfe_workspace.test-sourceable.id
}
```
workspace_id - (Required) The id of the workspace that owns the State Outputs. 
consumer_id - (Required) The ID of the consumer who wants to read the State Outputs.

Edit: Oops doubleup on #331

**Comment by ausmartway** [comment] 2021-10-13 00:20
@rorychatterton , with the tag system, managing tfe_workspace_remote_state_consumer_ids become much easier, not sure if you would adopt this as a solution:

```terraform
//get a list of TFC/E workspaces that has tag 'aws'
data "tfe_workspace_ids" "awsconsumer-apps" {
  tag_names    = ["awsconsumer"]
  organization = var.organization
}

resource "tfe_workspace" "aws-shared-infra" {
  description = "My core aws infrustructure that are shared by other workspaces."

  allow_destroy_plan        = true
  auto_apply                = true
  execution_mode            = "remote"
  file_triggers_enabled     = false
  global_remote_state       = false
  remote_state_consumer_ids = values(data.tfe_workspace_ids.awsconsumer-apps.ids)

  name = "aws-shared-infra"

  organization                  = var.organization
  queue_all_runs                = false
  speculative_enabled           = true
  structured_run_output_enabled = true
  tag_names                     = ["aws", "internal", "autoinject"]
  terraform_version             = "1.0.7"
  trigger_prefixes              = []

  vcs_repo {
    identifier         = "ausmartway/terraform-aws-core"
    ingress_submodules = false
    oauth_token_id     = local.tfc_oauth_token
  }

}
```

**Comment by rorychatterton** [comment] 2022-03-20 06:17
Sorry, not sure how I missed this response @ausmartway. This doesn't solve the problem I described earlier. If anything, it sort of introduces a circular dependency.

In the earlier example:

`Workspace A -----Provisions-----> Workspace B`
`Workspace B -----Consumes-----> Workspace A's Outputs`

To work with what you are suggesting, you need to add another workspace. (for this example, X). The run order would now look like:

1. Run Workspace X: Provision Workspace A
2. Run Workspace A: Provision Workspace B
3. Run Workspace X: Fetches Workspace B, and adds to Workspace A.

In small use cases, this is fine. At scale (Hundreds of workspaces), this is a clunky solution - particularly as Hashicorp charges per apply.

Still keen to see this split out as it continues to cause us pain.

**Comment by dbourcet** [comment] 2022-04-10 09:50
I also ran into this cycle error situation, when creating all our workspaces using a for_each : 
```
resource "tfe_workspace" "this" {
  for_each = {
    for workspace in local.workspaces : workspace.name => workspace
  }

  name                          = each.value.name
  [...]
  remote_state_consumer_ids  = will refer to tfe_workspace.this to retrieve ids
  [...]
  }
```
That means we can't handle workspaces creation into a single tfe_workspace resource.

It would be very nice to have a dedicated resource to configure remote_state_consumers_ids, such as the one for run_trigger:
https://registry.terraform.io/providers/hashicorp/tfe/0.27.0/docs/resources/run_trigger

**Comment by raynorg** [comment] 2022-06-30 22:41
I too hit this issue, and as a result am having to not use remote_state_consumer_ids. I'd love for it to be fixed, so I could properly codify the workspaces!

**Comment by niklong** [comment] 2022-07-18 02:13
Also hit this issue so I'm having to share state with all workspaces until there's another solution.

**Comment by brandonc** [comment] 2022-12-23 16:13
Closing this as a duplicate of #331, which we are treating as a planned feature in a future release

**Closed by brandonc** 2022-12-23 16:13 UTC
Labels: feature-request
