### ISSUE TITLE
tfe_notification_configuration - workspace_id vs workspace_external_id

### ISSUE THREAD

**Issue by jamesdagger-allocate** [hashicorp/terraform-provider-tfe#243] opened 2020-11-18 10:40 UTC
For tfe_notification_configuration. in the documentation workspace_external_id is flagged as - Deprecated
[https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/notification_configuration](url)

However, when using workspace_id instead, terraform appears to inform you of the contrary

`Error: Missing required argument`
`The argument "workspace_external_id" is required, but no definition was found.`

`Error: Unsupported argument`
`An argument named "workspace_id" is not expected here.`

**Comment by lafentres** [comment] 2020-11-20 20:33
Hi there! Could you share the following information?

1. What version of Terraform you're using
2. What version of the provider you're using
3. An simple config that reproduces the error you're seeing

Thanks!

**Comment by barrettclark** [comment] 2022-05-31 15:43
Closing due to lack of information

**Closed by barrettclark** 2022-05-31 15:43 UTC
Labels: bug, needs-more-info
