### ISSUE TITLE
tfe_output is showing empty value result

### ISSUE THREAD

**Issue by marcusricardoaguiar** [hashicorp/terraform-provider-tfe#933] opened 2023-06-16 12:26 UTC
#### Terraform Cloud/Enterprise version

I'm using Terraform Cloud.

#### Terraform version

Terraform Version: `1.3.9`

#### Terraform Configuration Files

This is the workspace (target) trying to get outputs from another workspace (source).

```terraform
data "tfe_outputs" "playground" {
  organization = "org-name"
  workspace    = "playground"
}

output "output_test" {
  value = data.tfe_outputs.playground.nonsensitive_values
}
```

#### Debug Output

I've been trying to read output values from one (source) workspace to a (target) workspace. When trying to "print" the values, I'm getting empty result:
![image](https://github.com/hashicorp/terraform-provider-tfe/assets/8216333/ad2ef5a3-d1f9-40b4-b94d-19322e52b890)

Even tough, my source workspace has the following output:

```terraform
data "google_compute_zones" "available" {
  region = "us-central1"
}

output "available" {
  value     = data.google_compute_zones.available.names
  sensitive = false
}
```

#### Expected Behavior
We should have values on the output, like below:
```terraform
output_test = {
    "available" = tolist([
        "us-central1-a",
        "us-central1-b",
        "us-central1-c",
        "us-central1-f",
    ])
}
```

#### Actual Behavior

I'm getting and empty value:
```terraform
output_test  = {}
```

**Comment by greggdingle** [comment] 2023-07-12 03:42
I am having the same problem as Marcus, but with Azure.

Terraform Client Version: 1.5.2
Terraform Cloud Workspace Version: 1.5.0
tfe Version: v0.46.0

Same code structure as what Marcus provided but with an Azure Key Vault id as the output parameter.

**Comment by ned1313** [comment] 2023-07-13 14:12
I have run into the same thing. Try going into the settings of the source workspace and sharing the state data with the target workspace. That should resolve the problem.

**Comment by sebasslash** [comment] 2023-07-17 20:18
So I'd like to get a bit more clarity on how exactly you're provisioning these workspaces (i.e in the same run or separate runs?). Outputs are populated asynchronously and therefore if provisioning on the same run, you need some way to await the outputs before you can utilize them in a downstream workspace (I do not recommend this). I was not able to reproduce your error provisioning each workspace in a separate run:

1. Create two working directories: `workspace-source` && `workspace-target`. 
2. Both dirs have a single config file `main.tf`:

Source Workspace:
```hcl
terraform { #omitting cloud backend def }

output "foo" {
  value = [
    "us-east-1a",
    "us-east-1b",
    "us-east-1c",
    "us-west-1a",
    "us-west-1b",
  ]
}

output "foo-sens" {
  value = {
    bar = "a"
  }
  sensitive = true
}
```
Target Workspace:
```hcl
terraform { # ditto }
provider "tfe" { # omitting }
provider "tfcoremock" {}

data "tfe_outputs" "foo" {
  organization = "foo"
  workspace = "bar"
}

resource "null_resource" "foo" {
  for_each = data.tfe_outputs.foo.nonsensitive_values
  provisioner "local-exec" {
    command = "echo ${each.key}=${jsonencode(each.value)}`
  }
}

resource "tfcoremock_simple_resource "bar" {
  string = data.tfe_outputs.foo.values.foo-sens.bar
}

output "test" {
  value = data.tfe_outputs.foo.values.foo-sens
}
```
3. Apply `workspace-source` via the CLI. Grab a coffee, let some time go by then apply `workspace-target`. 
4. Inspect the recently created state version for `workspace-target` and verify the correct values were fetched. 

Let me know if anything in my reproduction process deviated from yours.

**Comment by sebasslash** [comment] 2023-07-17 20:24
> I have run into the same thing. Try going into the settings of the source workspace and sharing the state data with the target workspace. That should resolve the problem.

This resolves the problem because it gives Terraform direct access to the remote state file, whereas "outputs" in TFC is a layer of abstraction with more granular access controls. It is generally not recommend to use the remote state data source because it requires you to have full state access on the workspace. If this isn't a concern, then it is a sufficient workaround because it ignores the asynchronous processing of TFC workspace outputs altogether.

**Comment by sebasslash** [comment] 2023-07-24 15:52
Following up @marcusricardoaguiar:
If you are in fact provisioning dependent workspaces in the same run, you may want to take a look at: [tfe_workspace_run](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/workspace_run). However this is slightly brittle as the resource only awaits the first and last run of a workspace. Alternatively, you can conditionally provision these workspaces using the ternary operator and the count meta arg `count = data.tfe_outputs.nonsensitive_values.foobar != tomap({}) ? 1 : 0`. This is extra hacky, because it would require a secondary run anyways and may destroy a resource if some output is intentionally set to the value in the conditional check. 

Still would like more information so I can best assist -- I have not been able to reproduce your bug.

**Comment by sebasslash** [comment] 2023-08-08 14:12
Closing for now, apologies. Please re-open if you need further assistance ❤️

**Closed by sebasslash** 2023-08-08 14:12 UTC
Labels: bug
